# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_likes',
        ),
    ]
